apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-read-role
  namespace: development
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "endpoints"]
    verbs: ["get", "watch", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-read-role-binding
  namespace: development
subjects:
  - kind: ServiceAccount
    name: default
    namespace: development
roleRef:
    kind: ClusterRole
    name: cluster-read-role
    apiGroup: rbac.authorization.k8s.io