apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-manager
  namespace: drone-transport
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-manager
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 300
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: kafka-manager
    spec:
      containers:
        - name: kafka-manager-container
          image: kafkamanager/kafka-manager
          ports:
            - containerPort: 9000
          imagePullPolicy: Always
          env:
            - name: ZK_HOSTS
              value: "drone-transport-kafka-zookeeper:2181"

---

apiVersion: v1
kind: Service
metadata:
  name: kafka-manager-service
  namespace: drone-transport
spec:
  selector:
    app: kafka-manager
  type: NodePort
  ports:
    - port: 9000
      targetPort: 9000

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-kafka-manager
  namespace: drone-transport
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: kafka.dashboard.kubernetes.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kafka-manager-service
                port:
                  number: 9000
