apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: weave-ingress
  namespace: weave
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: weave.dashboard.kubernetes.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: weave-scope-app
                port:
                  number: 80